### PR TITLE
replace initevent with new TouchEvent

### PR DESCRIPTION
**Pull request by RazgrizX**
Hi guys!
There is a small problem with the event creation.
The fix is really simple, so could you please merge it?
Tested it and it works, nothing really changes.
P.S. If you wont merge it, this error will keep to appear. It still works, but it is a Right way to resolve such issues anyway.
image

### CODE REVIEW

**Comment by conradlo** [comment]
Hello, thank you for your pull request.
Do you know if there will be any compatibility issues using `TouchEvent` ?

**Comment by RazgrizX** [comment]
Hi!
I don`t have a deep understanding of this matter, but it seems like straight upgrade.
Worked fine in my project.
Hmmm... seems like Safari lacks behind as usual with IE
image

**Comment by RazgrizX** [comment]
Wait... shouldn't the touch event work only on mobiles? Then it is a direct upgrade

**Comment by Fabchick** [comment]
I am getting the same error over and over again. As RazgrizX described there is nothing broken in functionality. It is just the error which appears.

Would be glad if this request will be merged.

**Comment by conradlo** [comment]
Hi, the latest version is updated. Thank you for letting me know.

**Pull request merged**
